"""added code complexity

Revision ID: 15321fe78f33
Revises: 79220630bce8
Create Date: 2022-11-29 11:18:53.927519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15321fe78f33'
down_revision = '79220630bce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_complexity_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('code_complexity_rank', sa.String(length=64), nullable=True))

    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lines_written', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('code_ownership', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_column('code_ownership')
        batch_op.drop_column('lines_written')

    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.drop_column('code_complexity_rank')
        batch_op.drop_column('code_complexity_value')

    # ### end Alembic commands ###
