"""repositories

Revision ID: 48f669d259f7
Revises: 11546a051ccc
Create Date: 2022-11-21 11:32:47.526143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f669d259f7'
down_revision = '11546a051ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], )
    )
    op.create_table('repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reponame', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_reponame'), ['reponame'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_reponame'))

    op.drop_table('repository')
    op.drop_table('members')
    # ### end Alembic commands ###
