"""removed old tables

Revision ID: 577db1f2e228
Revises: f5e0dcf64901
Create Date: 2022-11-21 13:57:44.880547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577db1f2e228'
down_revision = 'f5e0dcf64901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_table('viewers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewers',
    sa.Column('viewer_id', sa.INTEGER(), nullable=True),
    sa.Column('viewer_of_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['viewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['viewer_of_id'], ['user.id'], )
    )
    op.create_table('members',
    sa.Column('member_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
