"""added UserStats

Revision ID: 79220630bce8
Revises: 577db1f2e228
Create Date: 2022-11-24 13:40:40.006068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79220630bce8'
down_revision = '577db1f2e228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commit',
    sa.Column('author', sa.String(length=140), nullable=True),
    sa.Column('sha', sa.String(length=140), nullable=False),
    sa.Column('message', sa.String(length=140), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('time', sa.String(length=12), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('changes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sha')
    )
    with op.batch_alter_table('commit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commit_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_commit_message'), ['message'], unique=False)
        batch_op.create_index(batch_op.f('ix_commit_sha'), ['sha'], unique=True)

    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('days_committed', sa.Integer(), nullable=True),
    sa.Column('avg_freq', sa.Integer(), nullable=True),
    sa.Column('most_commits', sa.Integer(), nullable=True),
    sa.Column('least_commits', sa.Integer(), nullable=True),
    sa.Column('most_additions', sa.Integer(), nullable=True),
    sa.Column('least_additions', sa.Integer(), nullable=True),
    sa.Column('most_deletions', sa.Integer(), nullable=True),
    sa.Column('least_deletions', sa.Integer(), nullable=True),
    sa.Column('most_changes', sa.Integer(), nullable=True),
    sa.Column('least_changes', sa.Integer(), nullable=True),
    sa.Column('avg_no_additions', sa.Integer(), nullable=True),
    sa.Column('avg_no_deletions', sa.Integer(), nullable=True),
    sa.Column('avg_no_changes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['least_additions'], ['commit.sha'], ),
    sa.ForeignKeyConstraint(['least_changes'], ['commit.sha'], ),
    sa.ForeignKeyConstraint(['least_deletions'], ['commit.sha'], ),
    sa.ForeignKeyConstraint(['most_additions'], ['commit.sha'], ),
    sa.ForeignKeyConstraint(['most_changes'], ['commit.sha'], ),
    sa.ForeignKeyConstraint(['most_deletions'], ['commit.sha'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stats')
    with op.batch_alter_table('commit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commit_sha'))
        batch_op.drop_index(batch_op.f('ix_commit_message'))
        batch_op.drop_index(batch_op.f('ix_commit_author'))

    op.drop_table('commit')
    # ### end Alembic commands ###
