"""add viewers

Revision ID: ebf21e3fc509
Revises: 48f669d259f7
Create Date: 2022-11-21 13:44:40.409533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf21e3fc509'
down_revision = '48f669d259f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewers',
    sa.Column('viewer_id', sa.Integer(), nullable=True),
    sa.Column('viewer_of_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['viewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['viewer_of_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewers')
    # ### end Alembic commands ###
